#!/bin/bash  
backup='/tmp/giggity_IP'
ipreg='(\b[0-9]{1,3}\.){3}[0-9]{1,3}\b'
	egrep $ipreg $2 -nR | grep -v "127\.0\." | grep -v "0\.0\.0\.0" | cut -d: -f1,3 > $backup
case "$1" in
	'ips')
		cat $backup | cut -d: -f1 | xargs sed -r -i "s/$ipreg/giggity_IP/g" && echo -e "IPs from $2 have been removed \n\n more details at $backup"
	;;
	'restore')
		for i in `cat $backup| cut -d:1 -f1`; do
			sed -r -i "s/giggity_IP/$j/g" $i && echo -e "Production IPs have been restored"
		done
	;;
	*)
		echo -e  "\nUsage: $0 { ips | restore } followed by /mpath/to/sanitize_or_restore_to \n\n eg: sanitize ips /mpath/to/project\n\n"
	;;
esac
