#!/bin/bash
backup="/tmp/giggity_IP"
ipreg="[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}"

egrep $ipreg $1 -nR | grep -v "127\.0\." | grep -v "0\.0\.0\.0" | cut -d: -f1,2 > $backup

case "$1" in
'ips')
	sed -i 's/$ipreg/giggity_IP/g' $2 && echo "IPs from $2 have been removed"
	;;

'restore')
	for i j in $backup; do
		sed -i 's/giggity_IP/$j/g' $i && echo "Production IPs have been restored"
	done
	;;
*)
	echo "Usage: $0 { ips | restore }"
	;;
esac
